[general]
# Наверное стоит создавать локи в виде файлов во время операций с ВМ
# /var/node-agent/locks/vms/{vm}
locks_dir = '/var/node-agent/locks'

[libvirt]
uri = 'qemu:///system'

[logging]
level = 'INFO'
file = '/var/log/node-agent.log'

[volumes]

[[volumes.pools]]
name = 'ssd-nvme'
enabled = true
default = true
path = '/srv/vm-volumes/ssd-nvme'

[[volumes.pools]]
name = 'hdd'
enabled = true
path = '/srv/vm-volumes/hdd'

[vms.defaults]
# Какие-то значения по-умолчанию, используемые при создании/работе с ВМ
# Эти параметры также будут аффектить на CLI утилиты
autostart = true  # ставить виртуалки в автостарт после установки
start = true  # запускать ВМ после установки
cpu_vendor = 'Intel'
cpu_model = 'Broadwell'

[vms.images]
path = '/srv/vm-images'
