[libvirt]
uri = 'qemu:///system'

[logging]
level = 'INFO'
driver = 'file'
file = '/var/log/compute/compute.log'

[[storages.pools]]
name = 'ssd-nvme'
enabled = true
default = true
path = '/vm-volumes/ssd-nvme'

[[storages.pools]]
name = 'hdd'
enabled = true
path = '/vm-volumes/hdd'

[[storages.pools]]
name = 'images'
enabled = true
path = '/vm-images/vendor'

[virtual_machine.defaults]
autostart = true
start = true
cpu_vendor = 'Intel'
cpu_model = 'Broadwell'
